DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS visual;
DROP TABLE IF EXISTS auditory;

CREATE TABLE user (
  id TEXT PRIMARY KEY,
  nickname TEXT NOT NULL,
  age INTEGER NOT NULL,
  sex TEXT NOT NULL,
  phone_no TEXT
);

CREATE TABLE visual (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL,
  time INTEGER NOT NULL,
  mean INTEGER NOT NULL,
  data TEXT NOT NULL,
  FOREIGN KEY (user) REFERENCES user(id)
);

CREATE TABLE auditory (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL,
  time INTEGER NOT NULL,
  mean INTEGER NOT NULL,
  data TEXT NOT NULL,
  FOREIGN KEY (user) REFERENCES user(id)
);

CREATE INDEX idx_visual_user ON visual(user);
CREATE INDEX idx_auditory_user ON auditory(user);
